/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cadastro de aluno (cria sessão) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterInput"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicUser"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (cria sessão) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description Autenticado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicUser"];
                    };
                };
                /** @description Credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sem conteúdo */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthUser"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/specialties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista especialidades */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Specialty"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista cursos publicados */
        get: {
            parameters: {
                query?: {
                    specialty?: string;
                    level?: "iniciante" | "intermediario" | "avancado";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe do curso */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseDetail"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cursos matriculados do aluno */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrolledCourse"][];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player do curso (aulas com vídeo; exige matrícula) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoursePlayer"];
                    };
                };
                /** @description Não matriculado */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/lessons/{lessonId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca aula como concluída */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    lessonId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Registrado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Não matriculado */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/secretaria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Solicitações da secretaria do aluno */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SecretariaRequest"][];
                    };
                };
            };
        };
        put?: never;
        /** Abre uma solicitação de secretaria */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSecretariaInput"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SecretariaRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia o checkout de um curso (exige sessão) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCheckoutInput"];
                };
            };
            responses: {
                /** @description Pedido criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Já matriculado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta o pedido (polling do status de pagamento) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}/simulate-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simula a confirmação do pagamento (dev; substitui o webhook) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Confirmado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Order"];
                    };
                };
                /** @description Indisponível */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook de confirmação do gateway de pagamento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PaymentWebhookInput"];
                };
            };
            responses: {
                /** @description Recebido */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil do aluno */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza o nome do aluno */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Profile"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca a senha (exige a senha atual) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordInput"];
                };
            };
            responses: {
                /** @description Trocada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Senha atual incorreta */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{slug}/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Certificado de conclusão (curso 100% concluído) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Certificate"];
                    };
                };
                /** @description Curso não concluído */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Captura pública de lead (site) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateLeadInput"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lead"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPIs do painel (staff/admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Kpis"];
                    };
                };
                /** @description Sem permissão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kpis/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Série mensal de matrículas e receita (últimos 6 meses) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonthlyKpi"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos os cursos (inclui rascunhos) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourse"][];
                    };
                };
            };
        };
        put?: never;
        /** Cria um curso */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCourseInput"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourseDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista alunos com contagem de matrículas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Student"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista leads do funil de CRM */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lead"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe do curso (com módulos e aulas) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourseDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Exclui (soft-delete) um curso */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualiza/publica um curso */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCourseInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza estágio/notas de um lead */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateLeadInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Lead"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista oportunidades do funil de vendas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Opportunity"][];
                    };
                };
            };
        };
        put?: never;
        /** Cria uma oportunidade */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOpportunityInput"];
                };
            };
            responses: {
                /** @description Criada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Opportunity"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/opportunities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui uma oportunidade */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualiza uma oportunidade */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateOpportunityInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Opportunity"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/courses/{id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria um módulo no curso */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateModuleInput"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourseDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/modules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui um módulo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourseDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualiza um módulo */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateModuleInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourseDetail"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/modules/{id}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria uma aula no módulo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateLessonInput"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourseDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui uma aula */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourseDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualiza uma aula */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateLessonInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminCourseDetail"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/instructors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista instrutores */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Instructor"][];
                    };
                };
            };
        };
        put?: never;
        /** Cria um instrutor */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateInstructorInput"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Instructor"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/instructors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza um instrutor (nome/bio/avatar) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateInstructorInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Instructor"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuários (todos os papéis) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"][];
                    };
                };
            };
        };
        put?: never;
        /** Cria um usuário */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserInput"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"];
                    };
                };
                /** @description E-mail já cadastrado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Desativa (soft-delete) um usuário */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualiza nome/papel de um usuário */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Define nova senha para um usuário (reset) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matrículas de um usuário */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminEnrollment"][];
                    };
                };
            };
        };
        put?: never;
        /** Matricula um usuário em um curso */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EnrollUserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminEnrollment"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}/enrollments/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a matrícula de um usuário em um curso */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminEnrollment"][];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista canais de aquisição (com regras) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"][];
                    };
                };
            };
        };
        put?: never;
        /** Cria um canal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateChannelInput"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui um canal */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualiza um canal */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateChannelInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/channels/{id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adiciona uma regra ao canal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateChannelRuleInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/channels/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove uma regra */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualiza uma regra */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateChannelRuleInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Channel"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/admin/channels/leads-flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fluxo de leads por canal × estágio (janela opcional from/to) */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeadsFlow"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/channels/unmapped-origins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Origens (utm) sem regra de canal */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnmappedOrigin"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado do recurso de IA (habilitado quando há chave configurada) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ai/course-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gera um rascunho de curso a partir de material bruto (não persiste) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AiCourseDraftInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiCourseDraft"];
                    };
                };
                /** @description Rascunho inválido */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description IA indisponível */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterInput: {
            /** Format: email */
            email: string;
            password: string;
            name?: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        PublicUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string | null;
            /** @enum {string} */
            role: "aluno" | "staff" | "admin";
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "aluno" | "staff" | "admin";
        };
        Specialty: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description: string | null;
            icon: string | null;
        };
        CourseSummary: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            subtitle: string | null;
            priceCents: number;
            /** @enum {string} */
            level: "iniciante" | "intermediario" | "avancado";
            coverUrl: string | null;
            specialty: {
                slug: string;
                name: string;
            } | null;
            instructor: {
                slug: string;
                name: string;
                bio: string | null;
                avatarUrl: string | null;
            } | null;
        };
        CourseDetail: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            subtitle: string | null;
            priceCents: number;
            /** @enum {string} */
            level: "iniciante" | "intermediario" | "avancado";
            coverUrl: string | null;
            specialty: {
                slug: string;
                name: string;
            } | null;
            instructor: {
                slug: string;
                name: string;
                bio: string | null;
                avatarUrl: string | null;
            } | null;
            description: string | null;
            workloadHours: number | null;
            learningObjectives: string[];
            faq: {
                question: string;
                answer: string;
            }[];
            modules: {
                /** Format: uuid */
                id: string;
                title: string;
                position: number;
                lessons: {
                    /** Format: uuid */
                    id: string;
                    title: string;
                    durationSeconds: number;
                    isFree: boolean;
                }[];
            }[];
        };
        EnrolledCourse: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            coverUrl: string | null;
            specialty: {
                slug: string;
                name: string;
            } | null;
            progress: {
                completed: number;
                total: number;
                pct: number;
            };
        };
        CoursePlayer: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            subtitle: string | null;
            instructor: {
                name: string;
                avatarUrl: string | null;
            } | null;
            modules: {
                /** Format: uuid */
                id: string;
                title: string;
                position: number;
                lessons: {
                    /** Format: uuid */
                    id: string;
                    title: string;
                    durationSeconds: number;
                    vimeoVideoId: string | null;
                    completed: boolean;
                }[];
            }[];
        };
        SecretariaRequest: {
            /** Format: uuid */
            id: string;
            type: string;
            subject: string;
            body: string | null;
            /** @enum {string} */
            status: "open" | "in_progress" | "resolved";
            createdAt: string;
        };
        CreateSecretariaInput: {
            type: string;
            subject: string;
            body?: string;
        };
        Profile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string | null;
            /** @enum {string} */
            role: "aluno" | "staff" | "admin";
            createdAt: string;
        };
        UpdateProfileInput: {
            name: string;
        };
        ChangePasswordInput: {
            currentPassword: string;
            newPassword: string;
        };
        Certificate: {
            studentName: string;
            courseTitle: string;
            courseSlug: string;
            instructorName: string | null;
            lessonsTotal: number;
            completedAt: string;
        };
        CreateCheckoutInput: {
            courseSlug: string;
            /** @enum {string} */
            method: "pix" | "card" | "boleto";
            card?: {
                number: string;
                holderName: string;
                expMonth: number;
                expYear: number;
                cvv: string;
                /** @default 1 */
                installments: number;
            };
            attribution?: {
                utmSource?: string;
                utmMedium?: string;
                utmCampaign?: string;
                utmContent?: string;
                utmTerm?: string;
                referrer?: string;
                landingPath?: string;
                gclid?: string;
                fbclid?: string;
            };
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "pending" | "paid" | "cancelled" | "refunded";
            /** @enum {string} */
            method: "pix" | "card" | "boleto";
            amountCents: number;
            currency: string;
            installments: number;
            course: {
                slug: string;
                title: string;
                coverUrl: string | null;
            };
            pixQrCode: string | null;
            pixCopyPaste: string | null;
            boletoUrl: string | null;
            simulatable: boolean;
            createdAt: string;
        };
        PaymentWebhookInput: {
            event: string;
            providerChargeId: string;
            /** @enum {string} */
            status: "paid" | "failed" | "refunded";
        };
        CreateLeadInput: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            source?: string;
            attribution?: {
                utmSource?: string;
                utmMedium?: string;
                utmCampaign?: string;
                utmContent?: string;
                utmTerm?: string;
                referrer?: string;
                landingPath?: string;
                gclid?: string;
                fbclid?: string;
            };
        };
        Lead: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            phone: string | null;
            source: string;
            /** @enum {string} */
            stage: "new" | "contacted" | "qualified" | "won" | "lost";
            notes: string | null;
            utmSource: string | null;
            utmMedium: string | null;
            utmCampaign: string | null;
            createdAt: string;
        };
        Opportunity: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            stage: "prospeccao" | "qualificacao" | "proposta" | "negociacao" | "ganho" | "perdido";
            valueCents: number;
            probability: number;
            expectedCloseDate: string | null;
            /** Format: uuid */
            leadId: string | null;
            leadName: string | null;
            /** Format: uuid */
            ownerId: string | null;
            ownerName: string | null;
            createdAt: string;
        };
        CreateOpportunityInput: {
            title: string;
            /**
             * @default prospeccao
             * @enum {string}
             */
            stage: "prospeccao" | "qualificacao" | "proposta" | "negociacao" | "ganho" | "perdido";
            /** @default 0 */
            valueCents: number;
            /** @default 0 */
            probability: number;
            expectedCloseDate?: string | null;
            /** Format: uuid */
            leadId?: string | null;
            /** Format: uuid */
            ownerId?: string | null;
        };
        UpdateOpportunityInput: {
            title?: string;
            /** @enum {string} */
            stage?: "prospeccao" | "qualificacao" | "proposta" | "negociacao" | "ganho" | "perdido";
            valueCents?: number;
            probability?: number;
            expectedCloseDate?: string | null;
            /** Format: uuid */
            leadId?: string | null;
            /** Format: uuid */
            ownerId?: string | null;
        };
        Kpis: {
            students: number;
            activeEnrollments: number;
            publishedCourses: number;
            completionRate: number;
            estimatedRevenueCents: number;
            leadsByStage: {
                new: number;
                contacted: number;
                qualified: number;
                won: number;
                lost: number;
            };
        };
        MonthlyKpi: {
            month: string;
            label: string;
            enrollments: number;
            revenueCents: number;
            wonCents: number;
        };
        Channel: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            group: "pago" | "organico" | "base_propria";
            color: string;
            active: boolean;
            sortOrder: number;
            rules: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                channelId: string;
                utmSource: string;
                utmMedium: string | null;
                priority: number;
            }[];
        };
        CreateChannelInput: {
            name: string;
            /**
             * @default organico
             * @enum {string}
             */
            group: "pago" | "organico" | "base_propria";
            /** @default #3E7D5F */
            color: string;
            active?: boolean;
            sortOrder?: number;
            rules?: {
                utmSource: string;
                utmMedium?: string | null;
                priority?: number;
            }[];
        };
        UpdateChannelInput: {
            name?: string;
            /** @enum {string} */
            group?: "pago" | "organico" | "base_propria";
            color?: string;
            active?: boolean;
            sortOrder?: number;
        };
        CreateChannelRuleInput: {
            utmSource: string;
            utmMedium?: string | null;
            priority?: number;
        };
        UpdateChannelRuleInput: {
            utmSource?: string;
            utmMedium?: string | null;
            priority?: number;
        };
        LeadsFlow: {
            channels: {
                /** Format: uuid */
                id: string;
                name: string;
                /** @enum {string} */
                group: "pago" | "organico" | "base_propria";
                color: string;
                byStage: {
                    new: number;
                    contacted: number;
                    qualified: number;
                    won: number;
                    lost: number;
                    total: number;
                };
            }[];
            unmapped: {
                new: number;
                contacted: number;
                qualified: number;
                won: number;
                lost: number;
                total: number;
            };
            totals: {
                new: number;
                contacted: number;
                qualified: number;
                won: number;
                lost: number;
                total: number;
            };
        };
        UnmappedOrigin: {
            utmSource: string | null;
            utmMedium: string | null;
            count: number;
        };
        AdminCourse: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            /** @enum {string} */
            status: "draft" | "published";
            /** @enum {string} */
            level: "iniciante" | "intermediario" | "avancado";
            priceCents: number;
            createdAt: string;
        };
        AdminCourseDetail: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            subtitle: string | null;
            description: string | null;
            priceCents: number;
            /** @enum {string} */
            level: "iniciante" | "intermediario" | "avancado";
            /** @enum {string} */
            status: "draft" | "published";
            coverUrl: string | null;
            /** Format: uuid */
            specialtyId: string | null;
            /** Format: uuid */
            instructorId: string | null;
            workloadHours: number | null;
            learningObjectives: string[];
            faq: {
                question: string;
                answer: string;
            }[];
            modules: {
                /** Format: uuid */
                id: string;
                title: string;
                position: number;
                lessons: {
                    /** Format: uuid */
                    id: string;
                    title: string;
                    durationSeconds: number;
                    vimeoVideoId: string | null;
                    position: number;
                    isFree: boolean;
                }[];
            }[];
        };
        CreateCourseInput: {
            slug?: string;
            title: string;
            subtitle?: string | null;
            description?: string | null;
            /** @default 0 */
            priceCents: number;
            /**
             * @default iniciante
             * @enum {string}
             */
            level: "iniciante" | "intermediario" | "avancado";
            /**
             * @default draft
             * @enum {string}
             */
            status: "draft" | "published";
            /** Format: uri */
            coverUrl?: string | null;
            /** Format: uuid */
            specialtyId?: string | null;
            /** Format: uuid */
            instructorId?: string | null;
            workloadHours?: number | null;
            learningObjectives?: string[];
            faq?: {
                question: string;
                answer: string;
            }[];
        };
        CreateModuleInput: {
            title: string;
        };
        UpdateModuleInput: {
            title: string;
        };
        CreateLessonInput: {
            title: string;
            /** @default 0 */
            durationSeconds: number;
            vimeoVideoId?: string | null;
            /** @default false */
            isFree: boolean;
        };
        UpdateLessonInput: {
            title?: string;
            durationSeconds?: number;
            vimeoVideoId?: string | null;
            isFree?: boolean;
        };
        Instructor: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            bio: string | null;
            avatarUrl: string | null;
        };
        CreateInstructorInput: {
            name: string;
            bio?: string | null;
            /** Format: uri */
            avatarUrl?: string | null;
        };
        UpdateInstructorInput: {
            name?: string;
            bio?: string | null;
            /** Format: uri */
            avatarUrl?: string | null;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string | null;
            /** @enum {string} */
            role: "aluno" | "staff" | "admin";
            enrollments: number;
            createdAt: string;
        };
        AdminEnrollment: {
            /** Format: uuid */
            courseId: string;
            title: string;
            slug: string;
            /** @enum {string} */
            status: "active" | "completed" | "cancelled";
            createdAt: string;
        };
        EnrollUserInput: {
            /** Format: uuid */
            courseId: string;
        };
        CreateUserInput: {
            /** Format: email */
            email: string;
            name?: string | null;
            /**
             * @default aluno
             * @enum {string}
             */
            role: "aluno" | "staff" | "admin";
            password: string;
        };
        UpdateUserInput: {
            name?: string | null;
            /** @enum {string} */
            role?: "aluno" | "staff" | "admin";
        };
        ResetPasswordInput: {
            newPassword: string;
        };
        Student: {
            /** Format: uuid */
            id: string;
            name: string | null;
            email: string;
            enrollments: number;
            createdAt: string;
        };
        AiStatus: {
            enabled: boolean;
        };
        AiCourseDraftInput: {
            material: string;
            title?: string;
        };
        AiCourseDraft: {
            subtitle: string;
            description: string;
            workloadHours: number;
            learningObjectives: string[];
            faq: {
                question: string;
                answer: string;
            }[];
            modules: {
                title: string;
                lessons: {
                    title: string;
                    durationMinutes: number;
                }[];
            }[];
        };
        UpdateCourseInput: {
            slug?: string;
            title?: string;
            subtitle?: string | null;
            description?: string | null;
            priceCents?: number;
            /** @enum {string} */
            level?: "iniciante" | "intermediario" | "avancado";
            /** @enum {string} */
            status?: "draft" | "published";
            /** Format: uri */
            coverUrl?: string | null;
            /** Format: uuid */
            specialtyId?: string | null;
            /** Format: uuid */
            instructorId?: string | null;
            workloadHours?: number | null;
            learningObjectives?: string[];
            faq?: {
                question: string;
                answer: string;
            }[];
        };
        UpdateLeadInput: {
            /** @enum {string} */
            stage?: "new" | "contacted" | "qualified" | "won" | "lost";
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
